version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - ekart

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: flask
    ports:
      - "5432:5432"
    networks:
      - ekart

networks:
  ekart:
   driver: bridge
